### ISSUE TITLE
Want to deploy the oauth module on OpenMRS 1.11.6 

### ISSUE THREAD

**Issue by msahasrabuddhe** [harsha89/openmrs-module-oauth#2]
Hi Harsha,

I am looking to deploy the oauth module on version 1.11.6. But, when I deploy this module, I get an error message on the application stating that this module is compatible with version 1.12.0-SNAPSHOT. I tried to check if you have a branch for 1.11.6 but could not find one.

Do you know a solution to this?

Thanks,
Mandar

**Comment by maany** [comment]
Hey Mandar

The repo for the oauth module is currently maintained at http://github.com/maany/oauth2-module-prototype. Please check my response to your query there :)

**Comment by msahasrabuddhe** [comment]
Sounds good. I was not sure if the two modules have been developed separately or not. Hence, logged issues on both. :-) I will close this issue now.
